print ("super smash bros ultimite trivia")

answer = int(input("is there a kingdumb heart character in super smash bros ultimite.\n"))
print(answer == "yes")
answer = int(input("is tetris in super smash bros ultimite.\n"))
print(answer == "no")
answer = int(input("is the highest cpu in super smash bros ultimite 9.\n"))
print(answer == "yes")
answer = (input("is r.o.b in super smash bros ultimite.\n"))
print(answer == "yes")
answer = int(input(" is shadow in super smash bros ultimite.\n"))
print(answer == "no")