answer = int(input("Give a whole number that is less than 5.\n"))
print(answer < 5)
answer = int(input("Give a whole number that is more than 5.\n"))
print(answer > 5)
answer = int(input("is the highest cpu in super smash bros ultimite 9.\n"))
print(answer >= "yes")
answer = (input("is r.o.b in super smash bros ultimite.\n"))
print(answer == "yes")
answer = int(input(" is shadow in super smash bros ultimite.\n"))
print(answer == "no")